{{- if .Values.pdb.enabled }}
{{- if .Values.api.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ranking.fullname" . }}-api
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "ranking.labels" . | nindent 6 }}
      app.kubernetes.io/component: api
---
{{- end }}
{{- if .Values.platformWorker.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ranking.fullname" . }}-platform-worker
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "ranking.labels" . | nindent 6 }}
      app.kubernetes.io/component: platform-worker
---
{{- end }}
{{- if .Values.crawlWorker.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ranking.fullname" . }}-crawl-worker
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "ranking.labels" . | nindent 6 }}
      app.kubernetes.io/component: crawl-worker
{{- end }}
{{- end }}
