{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ranking.fullname" . }}-api
  labels:
    {{- include "ranking.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ranking.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
{{- end }}
