{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ranking.fullname" . }}-web
  labels:
    {{- include "ranking.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "ranking.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.port }}
{{- end }}
